#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,2,5,6,8,14,42,45,60,62,64&i=1,2,3,4,34,39&v=2,15,-1,21,33,5 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, XPT2046_Touchscreen */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */
#define L10N_LANGUAGE      RU

#define DSP_MODEL			DSP_ST7789
#define DSP_HSPI			true
#define TFT_DC			2
#define TFT_CS			15
#define BRIGHTNESS_PIN			21

// internal DAC
//#define I2S_INTERNAL			true
//#define PLAYER_FORCE_MONO true
//#define MUTE_PIN            4
//#define MUTE_VAL          HIGH

// I2S DAC
#define I2S_DOUT            22
#define I2S_BCLK            26
#define I2S_LRC             4

// SPDIF
#define SPDIF_OUT            22

#define TS_MODEL			TS_MODEL_XPT2046
#define TS_SPIPINS          25, 39, 32    /* SCK, MISO, MOSI */
#define TS_CS			33
#define SDC_CS			5
#define IR_PIN              34
#define AUTOBACKLIGHT_MAX   1024


#endif
